#!/usr/bin/env bash

output=$1
output_raw="$output.raw.eps"
input=$2
script=$3
rest=("${@:3}")

set -x
gnuplot -e "outputfile='$output_raw'" -e "inputfile='$input'" "${rest[@]}" "$script"
# epstool --copy --bbox "$output_raw" "$output"
# rm "$output_raw"
